### ISSUE TITLE
Strange error when switching themes

### ISSUE THREAD

**Issue by TheLoneTec** [Music-Expanded/music-expanded-framework#45]
https://gist.github.com/d2fee6534ca38f74538f3952b765b0c5

for some reason, when switching themes there are these strange errors (the music still plays fine) 

Could not load UnityEngine.Texture2D at MusicExpanded/Glitterworld/Glitterworld_Scenario_Begin in any active mod or in base resources.
Grain couldn't resolve: Clip not found at MusicExpanded/Glitterworld/Glitterworld_Scenario_Begin

it does this for all 3 event soundDef for all three playlists.

**Comment by Caaz** [comment]
Second time I've seen it, I think it's a mod compatibility issue but I'm not sure what. Since I'll be playing with things today I'll try some variations. I have a feeling like it's a misleading error. It's super super strange that it would try to get a texture from a sound.

The other report of this had something removing assets, but I don't think it's the same issue. 

Wonder if it has to do with the ogg change. 🤔 If so I'll run into it when I get to testing I guess.

**Comment by TheLoneTec** [comment]
i did try switching back to mp3 and it still did it. The only other mod that effects music i have is Rimthemes effecting menu music, but i disabled it and it still did it. so i am very confused.

**Comment by TheLoneTec** [comment]
ok found a mod that causes it, Customise Animals.

**Comment by Caaz** [comment]
You know what, you're the second person to mention that as well. I can take a look at it but ultimately that may be an unsolvable problem.

Hope it's open source 👀

**Comment by Caaz** [comment]
It appears CustomizeAnimals has updated to fix this problem! I shall close this now.
